version: '3'

services:
  pullenti:
    image: pullenti/pullenti-server
    restart: always
    ports:
      - 8080:8080

  deeppavlov:
    image: ${DEEPPAVLOV_IMAGE}
    restart: always
    ports:
      - 8081:6004

  texterra:
    image: natasha/texterra-russian
    restart: always
    ports:
      - 8082:8080

  mitie:
    image: natasha/mitie-ner-ru
    restart: always
    ports:
      - 8083:8080

  tomita:
    image: natasha/tomita-algfio
    restart: always
    ports:
      - 8084:8080

  natasha:
    image: natasha/natasha:0.10.0
    restart: always
    ports:
      - 8085:8080

  mongo:
    image: mongo:4.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Yax6mUVzdXzsCCo
    ports:
      - 27017:27017
    command: --wiredTigerCacheSizeGB=${DB_CACHE}

  worker:
    image: natasha/nerus-worker
    restart: always
    environment:
      DB_HOST: mongo
      DB_PORT: 27017
      DB_USERNAME: root
      DB_PASSWORD: Yax6mUVzdXzsCCo

      WORKER_ANNS: mitie,tomita,pullenti

      PULLENTI_HOST: pullenti
      PULLENTI_PORT: 8080

      DEEPPAVLOV_HOST: deeppavlov
      DEEPPAVLOV_PORT: 6004

      TEXTERRA_HOST: texterra
      TEXTERRA_PORT: 8080

      MITIE_HOST: mitie
      MITIE_PORT: 8080

      TOMITA_HOST: tomita
      TOMITA_PORT: 8080

      NATASHA_HOST: natasha
      NATASHA_PORT: 8080