
- hosts: worker

  become_user: root
  become: yes

  gather_facts: no

  tasks:

  # ##########
  # #
  # #  CUDA
  # #  https://developer.nvidia.com/cuda-90-download-archive?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu
  # #
  # ########

  # - name: Fetch CUDA Apt
  #   get_url:
  #     url: http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/cuda-repo-ubuntu1604_9.0.176-1_amd64.deb
  #     dest: /cuda.deb

  # - name: Add CUDA Apt
  #   apt:
  #     deb: /cuda.deb

  # - name: Add CUDA GPG
  #   apt_key:
  #     url: http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub

  # - name: Install CUDA
  #   apt:
  #     update_cache: yes
  #     name: cuda-9-0

  ##########
  #
  #  DOCKER
  #  https://docs.docker.com/install/linux/docker-ce/ubuntu/#set-up-the-repository
  #
  ########

  - name: Install Docker deps
    apt:
      update_cache: yes
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

  - name: Add Docker GPG
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg

  - name: Add Docker Apt
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable

  - name: Install Docker
    apt:
      name: docker-ce

  # ########
  # # 
  # #  NVIDIA DOCKER
  # #  https://github.com/NVIDIA/nvidia-docker
  # #
  # ########

  # - name: Add NVidia Docker GPG
  #   apt_key:
  #     url: https://nvidia.github.io/nvidia-docker/gpgkey

  # - name: Add NVidia Docker Apt
  #   get_url:
  #     url: https://nvidia.github.io/nvidia-docker/ubuntu16.04/nvidia-docker.list
  #     dest: /etc/apt/sources.list.d/nvidia-docker.list

  # - name: Install NVidia Docker
  #   apt:
  #     update_cache: yes
  #     name: nvidia-docker2

  # - name: Change Docker runtime
  #   copy:
  #     content: docker_daemon.json
  #     dest: /etc/docker/daemon.json

  # - name: Reboot
  #   reboot:

  ########
  #
  #   WORKER
  #
  ########

  - name: Install docker-compose
    get_url:
      url: https://github.com/docker/compose/releases/download/1.23.2/docker-compose-Linux-x86_64
      dest: /usr/bin/docker-compose
      mode: a+x

  - name: Copy docker-compose.yml
    copy:
      src: ../docker/docker-compose.yml
      dest: /docker-compose.yml

  - name: Copy .env
    copy:
      src: ../docker/cpu.env
      dest: /.env

  - name: Up compose
    command: chdir=/ docker-compose up -d
